name: PR Game Structure Check

on:
  pull_request:
    branches: [ main ]

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      games: ${{ steps.filter.outputs.games }}
      other: ${{ steps.filter.outputs.other }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            games:
              - 'games/**'
            other:
              - '*'
              - '!games/**'

  validate:
    needs: filter
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR contains changes outside games/
        if: needs.filter.outputs.other == 'true'
        run: |
          echo "Error: Only files under games/ are allowed in this PR." >&2
          exit 1

      - name: Skip if no changes in games/
        if: needs.filter.outputs.games == 'false'
        run: echo "No game-related changes detected, skipping validation."

      - name: Validate game directory
        if: needs.filter.outputs.games == 'true'
        run: |
          set -e
          BASE=${{ github.event.pull_request.base.sha }}
          HEAD=${{ github.event.pull_request.head.sha }}
          git fetch origin "$BASE" --depth=1

          files=$(git diff --name-only "$BASE" "$HEAD")
          dirs=$(echo "$files" | grep '^games/' | cut -d/ -f2 | sort -u)
          count=$(echo "$dirs" | wc -l | tr -d ' ')

          if [ "$count" -ne 1 ]; then
            echo "Error: PR must modify exactly one directory under games/ (found $count)." >&2
            exit 1
          fi

          dir=$(echo "$dirs")
          if [[ ! "$dir" =~ ^[a-z]+(-[a-z]+)*$ ]]; then
            echo "Error: Directory name '$dir' invalid; use lowercase words separated by hyphens." >&2
            exit 1
          fi

          required=(README.md style.css index.html game.js game.json)
          missing=()
          for f in "${required[@]}"; do
            [ -f "games/$dir/$f" ] || missing+=("$f")
          done

          if [ ${#missing[@]} -gt 0 ]; then
            echo "Error: games/$dir missing required files: ${missing[*]}" >&2
            exit 1
          fi

          echo "✅ Structure validation passed for games/$dir."
